---------------------------------------
Begin Slurm Prolog: Jun-29-2025 18:16:24
Job ID:    5638110
User ID:   cfilho3
Account:   gts-itaboada3
Job name:  DeepIceL40sMixed
Partition: gpu-l40s
QOS:       embers
---------------------------------------
Logs â†’ /storage/home/hcoda1/8/cfilho3/p-itaboada3-0/graphnet/carlos_tests/icemix/telemetry_5638110
Job started at Sun Jun 29 18:16:30 EDT 2025
Job ID: 5638110
Job name: DeepIceL40sMixed
Job queue: 
Job partition: gpu-l40s
Job nodes: atl1-1-03-004-31-0
Starting GPU monitor...
Starting system monitor...
Training started...
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-29 18:16:45 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250629-181645.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-29 18:16:45 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250629-181645.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-29 18:16:45 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250629-181645.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-29 18:16:45 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250629-181645.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-29 18:16:45 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250629-181645.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-29 18:16:45 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250629-181645.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-29 18:16:45 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250629-181645.log[0m
[1;34mgraphnet[0m [MainProcess] [32mINFO    [0m 2025-06-29 18:16:45 - NodesAsPulses.__init__ - Writing log to [1mlogs/graphnet_20250629-181645.log[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-29 18:16:45 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-29 18:16:45 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-29 18:16:45 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-29 18:16:45 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-29 18:16:45 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-29 18:16:45 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-29 18:16:45 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
[1;34mgraphnet[0m [MainProcess] [33mWARNING [0m 2025-06-29 18:16:45 - has_icecube_package - `icecube` not available. Some functionality may be missing.[0m
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "train_icemix_mixed.py", line 36, in <module>
  File "train_icemix_mixed.py", line 36, in <module>
  File "train_icemix_mixed.py", line 36, in <module>
  File "train_icemix_mixed.py", line 36, in <module>
  File "train_icemix_mixed.py", line 36, in <module>
  File "train_icemix_mixed.py", line 36, in <module>
  File "train_icemix_mixed.py", line 36, in <module>
Traceback (most recent call last):
  File "train_icemix_mixed.py", line 36, in <module>
    from utils import (
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 111, in <module>
    from utils import (        
from utils import (        from utils import (

  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 111, in <module>
    from utils import (from utils import (  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 111, in <module>


  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 111, in <module>
from utils import (
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 111, in <module>
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 111, in <module>
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 111, in <module>
    from utils import (
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 111, in <module>
    NuMu_Training_Selections = load_list_from_csv(NumuTraining)
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 29, in load_list_from_csv
    NuMu_Training_Selections = load_list_from_csv(NumuTraining)
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 29, in load_list_from_csv
        NuMu_Training_Selections = load_list_from_csv(NumuTraining)NuMu_Training_Selections = load_list_from_csv(NumuTraining)

  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 29, in load_list_from_csv
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 29, in load_list_from_csv
    NuMu_Training_Selections = load_list_from_csv(NumuTraining)
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 29, in load_list_from_csv
    NuMu_Training_Selections = load_list_from_csv(NumuTraining)
      File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 29, in load_list_from_csv
NuMu_Training_Selections = load_list_from_csv(NumuTraining)
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 29, in load_list_from_csv
        df = pd.read_csv(csv_file_path, dtype={"event_no": int})    df = pd.read_csv(csv_file_path, dtype={"event_no": int})
df = pd.read_csv(csv_file_path, dtype={"event_no": int})

  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
            df = pd.read_csv(csv_file_path, dtype={"event_no": int})df = pd.read_csv(csv_file_path, dtype={"event_no": int})NuMu_Training_Selections = load_list_from_csv(NumuTraining)


  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
  File "/storage/coda1/p-itaboada3/0/cfilho3/graphnet/carlos_tests/icemix/utils.py", line 29, in load_list_from_csv
    df = pd.read_csv(csv_file_path, dtype={"event_no": int})
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    df = pd.read_csv(csv_file_path, dtype={"event_no": int})
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    df = pd.read_csv(csv_file_path, dtype={"event_no": int})
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
        return _read(filepath_or_buffer, kwds)    return _read(filepath_or_buffer, kwds)
    return _read(filepath_or_buffer, kwds)
return _read(filepath_or_buffer, kwds)
    
          File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
      File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
return _read(filepath_or_buffer, kwds)  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
return _read(filepath_or_buffer, kwds)  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read

return _read(filepath_or_buffer, kwds)return _read(filepath_or_buffer, kwds)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read


  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
      File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self._engine = self._make_engine(f, self.engine)    
    self._engine = self._make_engine(f, self.engine)self._engine = self._make_engine(f, self.engine)  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine


  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self._engine = self._make_engine(f, self.engine)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
        self._engine = self._make_engine(f, self.engine)self._engine = self._make_engine(f, self.engine)

  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self._engine = self._make_engine(f, self.engine)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
        self.handles = get_handle(self.handles = get_handle(

  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
      File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
self.handles = get_handle(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    self.handles = get_handle(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    self.handles = get_handle(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    self.handles = get_handle(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    self.handles = get_handle(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    self.handles = get_handle(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
            handle = open(    handle = open(        handle = open(        

handle = open(handle = open(handle = open(
handle = open(handle = open(


FileNotFoundError
FileNotFoundError
FileNotFoundErrorFileNotFoundErrorFileNotFoundErrorFileNotFoundError: : FileNotFoundError: FileNotFoundError: : [Errno 2] No such file or directory: '/storage/home/hcoda1/8/cfilho3/p-itaboada3-0/graphnet/carlos_tests/icemix/data/resultstitoclassnumu_training_selection.csv': : [Errno 2] No such file or directory: '/storage/home/hcoda1/8/cfilho3/p-itaboada3-0/graphnet/carlos_tests/icemix/data/resultstitoclassnumu_training_selection.csv'[Errno 2] No such file or directory: '/storage/home/hcoda1/8/cfilho3/p-itaboada3-0/graphnet/carlos_tests/icemix/data/resultstitoclassnumu_training_selection.csv': 

[Errno 2] No such file or directory: '/storage/home/hcoda1/8/cfilho3/p-itaboada3-0/graphnet/carlos_tests/icemix/data/resultstitoclassnumu_training_selection.csv'[Errno 2] No such file or directory: '/storage/home/hcoda1/8/cfilho3/p-itaboada3-0/graphnet/carlos_tests/icemix/data/resultstitoclassnumu_training_selection.csv'
[Errno 2] No such file or directory: '/storage/home/hcoda1/8/cfilho3/p-itaboada3-0/graphnet/carlos_tests/icemix/data/resultstitoclassnumu_training_selection.csv'[Errno 2] No such file or directory: '/storage/home/hcoda1/8/cfilho3/p-itaboada3-0/graphnet/carlos_tests/icemix/data/resultstitoclassnumu_training_selection.csv'

[Errno 2] No such file or directory: '/storage/home/hcoda1/8/cfilho3/p-itaboada3-0/graphnet/carlos_tests/icemix/data/resultstitoclassnumu_training_selection.csv'


[2025-06-29 18:16:48,687] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 4038849) of binary: /storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/bin/python3.8
Traceback (most recent call last):
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/storage/home/hcoda1/8/cfilho3/.conda/envs/graphnet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_icemix_mixed.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-06-29_18:16:48
  host      : atl1-1-03-004-31-0.pace.gatech.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 4038850)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-06-29_18:16:48
  host      : atl1-1-03-004-31-0.pace.gatech.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 4038851)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2025-06-29_18:16:48
  host      : atl1-1-03-004-31-0.pace.gatech.edu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 4038852)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2025-06-29_18:16:48
  host      : atl1-1-03-004-31-0.pace.gatech.edu
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 4038853)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2025-06-29_18:16:48
  host      : atl1-1-03-004-31-0.pace.gatech.edu
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 4038854)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2025-06-29_18:16:48
  host      : atl1-1-03-004-31-0.pace.gatech.edu
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 4038855)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2025-06-29_18:16:48
  host      : atl1-1-03-004-31-0.pace.gatech.edu
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 4038856)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-06-29_18:16:48
  host      : atl1-1-03-004-31-0.pace.gatech.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4038849)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: atl1-1-03-004-31-0: task 0: Exited with exit code 1
Training finished with code 1 - stopping monitors...
All done at Sun Jun 29 18:16:48 EDT 2025
---------------------------------------
Begin Slurm Epilog: Jun-29-2025 18:16:50
Job ID:        5638110
User ID:       cfilho3
Account:       gts-itaboada3
Job name:      DeepIceL40sMixed
Resources:     cpu=32,gres/gpu:l40s=8,mem=506808M,node=1
Rsrc Used:     cput=00:13:52,vmem=0,walltime=00:00:26,mem=36852K,energy_used=0
Partition:     gpu-l40s
QOS:           embers
Nodes:         atl1-1-03-004-31-0
---------------------------------------
